export const recipes = [
  {
    id: 1,
    title: 'Spaghetti Carbonara',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/3/33/Espaguetis_carbonara.jpg',
    shortDescription: 'Pasta with a creamy egg and cheese sauce.',
    steps: ['Cook the pasta.', 'Fry pancetta.', 'Mix with egg and cheese.', 'Serve with parsley.'],
    preparationTime: '30 minutes',
    ingredients: [
      'spaghetti',
      'pancetta or bacon',
      'eggs',
      'Parmesan cheese',
      'olive oil',
      'salt',
      'pepper',
    ],
  },
  {
    id: 2,
    title: 'Tacos al Pastor',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/4a/Tacos-al-Pastor.jpg',
    shortDescription: 'Tacos with marinated pork and pineapple.',
    steps: [
      'Marinate the meat.',
      'Cook on the spit.',
      'Serve in tortillas with onions and cilantro.',
    ],
    preparationTime: '1 hour 30 minutes',
    ingredients: [
      'pork shoulder',
      'pineapple',
      'tortillas',
      'onions',
      'cilantro',
      'achiote paste',
      'guajillo chiles',
      'garlic',
      'oregano',
      'vinegar',
      'orange juice',
    ],
  },
  {
    id: 3,
    title: 'Caesar Salad',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/23/Caesar_salad_%282%29.jpg',
    shortDescription: 'Fresh salad with lettuce, croutons, and Caesar dressing.',
    steps: ['Mix lettuce and croutons.', 'Add Caesar dressing.', 'Sprinkle with Parmesan cheese.'],
    preparationTime: '15 minutes',
    ingredients: [
      'romaine lettuce',
      'croutons',
      'Caesar dressing',
      'Parmesan cheese',
      'olive oil',
      'lemon juice',
      'garlic',
      'anchovies',
      'Worcestershire sauce',
      'Dijon mustard',
    ],
  },
  {
    id: 4,
    title: 'Valencian Paella',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/a/ae/Paella_Valenciana.jpg',
    shortDescription: 'Rice dish with seafood and chicken.',
    steps: [
      'Sauté vegetables.',
      'Add rice and broth.',
      'Add seafood and chicken.',
      'Cook on low heat.',
    ],
    preparationTime: '1 hour 30 minutes',
    ingredients: [
      'short-grain rice',
      'chicken',
      'rabbit',
      'green beans',
      'butter beans',
      'artichokes',
      'tomatoes',
      'saffron',
      'paprika',
      'olive oil',
      'garlic',
      'rosemary',
      'thyme',
    ],
  },
  {
    id: 5,
    title: 'Margherita Pizza',
    imageUrl:
      'https://upload.wikimedia.org/wikipedia/commons/2/2d/Punch_Neapolitan_Pizza_Margherita.jpg',
    shortDescription: 'Classic pizza with tomato, mozzarella, and basil.',
    steps: ['Prepare the dough.', 'Add tomato sauce and cheese.', 'Bake and add fresh basil.'],
    preparationTime: '1 hour 30 minutes',
    ingredients: [
      'pizza dough',
      'tomato sauce',
      'mozzarella cheese',
      'fresh basil',
      'olive oil',
      'salt',
    ],
  },
  {
    id: 6,
    title: 'Sushi Roll',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/7/7b/Sushi_Roll.jpg',
    shortDescription: 'Sushi rolls with fish and vegetables.',
    steps: ['Cook the rice.', 'Roll with seaweed and filling.', 'Cut into pieces and serve.'],
    preparationTime: '45 minutes',
    ingredients: ['sushi rice', 'seaweed', 'fish', 'vegetables', 'soy sauce', 'wasabi'],
  },
  {
    id: 7,
    title: 'Chili con Carne',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/24/Chili_con_carne.jpg',
    shortDescription: 'Spicy stew with meat and beans.',
    steps: ['Sauté onion and garlic.', 'Add meat and spices.', 'Incorporate beans and simmer.'],
    preparationTime: '1 hour 30 minutes',
    ingredients: [
      'ground beef',
      'onion',
      'garlic',
      'chili powder',
      'cumin',
      'paprika',
      'red kidney beans',
      'tomatoes',
      'bell peppers',
      'salt',
      'pepper',
    ],
  },
  {
    id: 8,
    title: 'Sweet Crepes',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/0/09/Crepes_dsc07085.jpg',
    shortDescription: 'Delicious crepes filled with Nutella and fruits.',
    steps: ['Prepare crepe batter.', 'Cook in a skillet.', 'Fill and fold.'],
    preparationTime: '30 minutes',
    ingredients: [
      'flour',
      'eggs',
      'milk',
      'sugar',
      'vanilla extract',
      'butter',
      'Nutella',
      'fresh fruits',
    ],
  },
  {
    id: 9,
    title: 'Pasta Pesto',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/8/89/Pasta_with_pesto.jpg',
    shortDescription: 'Pasta with basil and pine nut sauce.',
    steps: ['Cook the pasta.', 'Blend basil, pine nuts, and oil.', 'Combine with pasta.'],
    preparationTime: '20 minutes',
    ingredients: [
      'pasta',
      'basil leaves',
      'pine nuts',
      'garlic',
      'Parmesan cheese',
      'olive oil',
      'salt',
      'pepper',
    ],
  },
  {
    id: 10,
    title: 'Lentil Stew',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/1e/Red_lentil_soup.jpg',
    shortDescription: 'Healthy stew with lentils and vegetables.',
    steps: ['Sauté onion and garlic.', 'Add lentils and broth.', 'Cook with vegetables.'],
    preparationTime: '1 hour',
    ingredients: [
      'lentils',
      'onion',
      'garlic',
      'carrots',
      'celery',
      'potatoes',
      'vegetable broth',
      'tomatoes',
      'spices',
      'herbs',
    ],
  },
  {
    id: 11,
    title: 'Oven Roasted Chicken',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/a/a3/Chicken.png',
    shortDescription: 'Juicy chicken roasted with herbs.',
    steps: ['Marinate the chicken.', 'Place in a baking tray and roast.', 'Serve with sides.'],
    preparationTime: '1 hour 30 minutes',
    ingredients: [
      'whole chicken',
      'lemon',
      'garlic',
      'rosemary',
      'thyme',
      'olive oil',
      'salt',
      'pepper',
    ],
  },
  {
    id: 12,
    title: 'Spanish Omelette',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/41/Tortilla_patatas.jpg',
    shortDescription: 'Omelette made with potatoes and onion.',
    steps: ['Sauté the potatoes.', 'Beat the eggs.', 'Mix and cook in a skillet.'],
    preparationTime: '45 minutes',
    ingredients: ['potatoes', 'onion', 'eggs', 'olive oil', 'salt', 'pepper'],
  },
  {
    id: 13,
    title: 'Chocolate Brownies',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/3/3e/Chocolate_brownie.jpg',
    shortDescription: 'Delicious brownies with chocolate chunks.',
    steps: ['Mix dry ingredients.', 'Add eggs and butter.', 'Bake and cut into squares.'],
    preparationTime: '45 minutes',
    ingredients: [
      'flour',
      'cocoa powder',
      'sugar',
      'eggs',
      'butter',
      'chocolate chunks',
      'vanilla extract',
      'baking powder',
    ],
  },
  {
    id: 14,
    title: 'Gazpacho',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/1e/Gazpacho.jpg',
    shortDescription: 'Cold soup made with tomatoes and vegetables.',
    steps: ['Blend tomatoes, cucumber, and peppers.', 'Add oil and vinegar.', 'Serve cold.'],
    preparationTime: '30 minutes',
    ingredients: [
      'tomatoes',
      'cucumber',
      'bell peppers',
      'olive oil',
      'vinegar',
      'garlic',
      'salt',
      'bread',
    ],
  },
  {
    id: 15,
    title: 'Classic Hamburger',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/4/4d/Cheeseburger.jpg',
    shortDescription: 'Juicy hamburger with cheese and vegetables.',
    steps: ['Shape the patties.', 'Cook on the grill.', 'Assemble with buns and toppings.'],
    preparationTime: '30 minutes',
    ingredients: [
      'ground beef',
      'hamburger buns',
      'cheese',
      'lettuce',
      'tomatoes',
      'onions',
      'ketchup',
      'mustard',
      'salt',
      'pepper',
    ],
  },
  {
    id: 16,
    title: 'Chocolate Mousse',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/f/f0/Chocolate_mousse.jpg',
    shortDescription: 'Light and creamy chocolate dessert.',
    preparationTime: '20 min',
    ingredients: ['Dark chocolate', 'Eggs', 'Sugar', 'Heavy cream'],
    steps: ['Melt chocolate.', 'Whip the egg whites.', 'Mix and chill.'],
  },
  {
    id: 17,
    title: 'Pancakes',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/3/34/Make_a_pancake.jpg',
    shortDescription: 'Fluffy pancakes served with syrup.',
    preparationTime: '25 min',
    ingredients: ['Flour', 'Milk', 'Eggs', 'Baking powder', 'Butter', 'Sugar'],
    steps: ['Mix the batter.', 'Cook on a griddle.', 'Serve with syrup and fruit.'],
  },
  {
    id: 18,
    title: 'Caprese Salad',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/6/6e/Caprese.jpg',
    shortDescription: 'Fresh salad with tomatoes, mozzarella, and basil.',
    preparationTime: '10 min',
    ingredients: ['Tomatoes', 'Mozzarella', 'Basil', 'Olive oil', 'Salt', 'Pepper'],
    steps: ['Slice tomatoes and mozzarella.', 'Layer with basil.', 'Drizzle with olive oil.'],
  },
  {
    id: 19,
    title: 'Beef Stroganoff',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/f/f1/Stroganoff.jpg',
    shortDescription: 'Creamy beef dish served over noodles.',
    preparationTime: '40 min',
    ingredients: ['Beef', 'Onions', 'Mushrooms', 'Sour cream', 'Beef broth', 'Garlic', 'Butter'],
    steps: ['Sauté beef and onions.', 'Add sour cream and broth.', 'Serve over noodles.'],
  },
]
